version: "3.9"

services:
  db:
    image: postgres:16
    container_name: postgres_final_test
    environment:
      POSTGRES_USER: challenge
      POSTGRES_PASSWORD: challenge
      POSTGRES_DB: challenge
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U challenge -d challenge"]
      interval: 5s
      timeout: 3s
      retries: 10